actions:
  to: kubernetes/overlays/base/service.yaml
---

kind: Service
apiVersion: v1
metadata:
  name: service
spec:
  # type: LoadBalancer
  sessionAffinity: None
  ports:
    - port: 80
      targetPort: 8080